services:
  napcat:
    image: mlikiowa/napcat-docker:v4.18.5
    container_name: napcat
    restart: always
    environment:
      - NAPCAT_UID=${NAPCAT_UID:-1000}
      - NAPCAT_GID=${NAPCAT_GID:-1000}
    ports:
      - "6099:6099"
    volumes:
      - ./napcat/config:/app/napcat/config
      - ./napcat/plugins:/app/napcat/plugins
      - ./ntqq:/app/.config/QQ
    networks:
      - ww_network

  gsuid_core:
    image: docker.cnb.cool/gscore-mirror/gsuid_core:latest
    container_name: gsuid_core
    restart: always
    environment:
      - UV_HTTP_TIMEOUT=300
      - UV_HTTP_RETRIES=10
      - UV_DEFAULT_INDEX=https://pypi.tuna.tsinghua.edu.cn/simple
    ports:
      - "8765:8765"
    volumes:
      - ./gscore/data:/gsuid_core/data
      - ./gscore/plugins:/gsuid_core/gsuid_core/plugins
      - gsuid_core_venv:/venv
    networks:
      - ww_network

networks:
  ww_network:
    driver: bridge

volumes:
  gsuid_core_venv:
